name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Stats Light
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&include_all_commits=true&count_private=true
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Dark
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=7&theme=tokyonight
          path: profile/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Light
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=7&theme=default
          path: profile/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Activity Dark
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&include_all_commits=true
          path: profile/activity-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Activity Light
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default&include_all_commits=true
          path: profile/activity-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated statistics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git commit -m "chore: update GitHub profile statistics" || exit 0

          git push